//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscountOptionDataWeb.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
   
    using DiscountOptionDataWeb.Data;

    public  class PaymentsModel : DbContext, DiscountOptionDataWeb.Data.IPaymentsModel
    {
        public PaymentsModel()
            : base("name=OptionDataCenterConnnection")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //03/29/18
            Database.SetInitializer<PaymentsModel>(null);
            base.OnModelCreating(modelBuilder);
            //throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }


    }
}
